spring.application.name=bnk_final_ap
server.port=8090

# =======================
# ORACLE (메인 JPA 데이터소스)
# =======================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:testdb
spring.datasource.username=green
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# =======================
# PostgreSQL(pgvector)
# -> DataSource를 수동 등록할 예정 (Spring JPA가 사용 안 함)
# =======================
pg.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
pg.datasource.username=myuser
pg.datasource.password=secret
pg.datasource.driver-class-name=org.postgresql.Driver

# =======================
# OpenAI API Key & Model 설정
# =======================
openai.api.key=#
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.embedding.options.model=text-embedding-3-small

#
#
#pdf.etf.path=src/main/resources/static/pdf/etf
#pdf.tdf.path=src/main/resources/static/pdf/tdf
#pdf.pg.path=src/main/resources/static/pdf/pg
#pdf.fund.path=src/main/resources/static/pdf/fund
#pdf.default.path=src/main/resources/static/pdf/default
#
#logging.level.org.apache.fontbox.ttf=ERROR
