spring.application.name=bnk_final_ap
server.port=8090

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@192.168.0.236:1521:testdb
spring.datasource.username=green
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


pg.datasource.url=jdbc:postgresql://localhost:5432/pension_vector_db?reWriteBatchedInserts=true
pg.datasource.username=pension_user
pg.datasource.password=1234
pg.datasource.driver-class-name=org.postgresql.Driver


spring.ai.openai.api-key=#
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.jpa.properties.hibernate.jdbc.batch_size=200
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


kakao.rest-key=#
logging.level.org.apache.fontbox.ttf=ERROR

crypto.key=ThisIsMySecretKeyForProject12345
crypto.iv=MyUniqueIvIs16By

clova.ocr.url=#
clova.ocr.secret=#
family.ocr.template-id=#

app.aws.access-key-id=#
app.aws.secret-access-key=#
spring.cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket-name=irp-couple-link

